version: '3.8'
services:
  it-dropzones:
    image: argitasuna/it-dropzones:latest
    container_name: it-dropzones
    ports:
      - "8080:5000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      DEFAULT_LANG: en  # fr | en | eu 
      DEFAULT_THEME: natura  # iluna | natura | amber | zuri-beltz | beltz-zuri
    restart: unless-stopped
