services:
  it-dropzones:
    image: argitasuna/it-dropzones:latest
    container_name: it-dropzones
    ports:
      - "5000:5000"
    environment:
      PASSWORD: yourpassword
      DEFAULT_LANG: en
      DEFAULT_THEME: natura  # iluna | natura | amber | zuri-beltz | beltz-zuri | marrazkia
      # SECRET_KEY: set this explicitly if you run multiple workers/instances
    volumes:
      - ./itdropzones:/app/uploads
    restart: unless-stopped
